# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0 filetype=yaml:

# This CI uses the freedesktop.org ci-templates.
# Please see the ci-templates documentation for details:
# https://freedesktop.pages.freedesktop.org/ci-templates/

.templates_sha: &template_sha 25e8e9f020880aa35fffe3d6b259b933f0f9449f # see https://docs.gitlab.com/ee/ci/yaml/#includefile


include:
  # Arch container builder template
  - project: 'freedesktop/ci-templates'
    ref: *template_sha
    file: '/templates/arch.yml'
  - project: 'freedesktop/ci-templates'
    ref: *template_sha
    file: '/templates/ci-fairy.yml'
  - template: Security/SAST.gitlab-ci.yml


stages:
  - prep             # prep work like rebuilding the container images if there is a change
  - build            # for actually building and testing things in a container
  - test
  - deploy


variables:
  FDO_UPSTREAM_REPO: 'xorg/lib/libXau'
  # The tag should be updated each time the list of packages is updated.
  # Changing a tag forces the associated image to be rebuilt.
  # Note: the tag has no meaning, we use a date format purely for readability
  FDO_DISTRIBUTION_TAG:  '2023-09-16'
  FDO_DISTRIBUTION_PACKAGES:  'git gcc clang pkgconf autoconf automake libtool make xorg-util-macros xorgproto meson ninja jq'


#
# Verify that commit messages are as expected
#
check-commits:
  extends:
    - .fdo.ci-fairy
  stage: prep
  script:
    - ci-fairy check-commits --junit-xml=results.xml
  except:
    - master@xorg/lib/libXau
  variables:
    GIT_DEPTH: 100
  artifacts:
    reports:
      junit: results.xml

#
# Verify that the merge request has the allow-collaboration checkbox ticked
#
check-merge-request:
  extends:
    - .fdo.ci-fairy
  stage: deploy
  script:
    - ci-fairy check-merge-request --require-allow-collaboration --junit-xml=results.xml
  artifacts:
    when: on_failure
    reports:
      junit: results.xml
  allow_failure: true


#
# Build a container with the given tag and the packages pre-installed.
# This only happens if/when the tag changes, otherwise the existing image is
# re-used.
#
container-prep:
  extends:
    - .fdo.container-build@arch
  stage: prep
  variables:
    GIT_STRATEGY: none


#
# The autotools build, runs on the image built above.
#
autotools:
  stage: build
  extends:
    - .fdo.distribution-image@arch
  script:
    - autoreconf -ivf
    - mkdir _builddir
    - pushd _builddir > /dev/null
    - ../configure --disable-silent-rules
    - make
    - make check
    - make distcheck
    - mv libXau*.tar.gz ..
    - popd > /dev/null
  artifacts:
    paths:
      - libXau*.tar.gz

#
# The meson build, runs on the image built above.
#
.meson_build:
  stage: build
  extends:
    - .fdo.distribution-image@arch
  script:
    - CC="${CC}" meson setup _builddir --prefix="$PWD/_install"
    - meson configure _builddir
    - ninja -C _builddir test
    - ninja -C _builddir install

# Run meson build with different compilers
meson:
  extends:
    - .meson_build
  parallel:
    matrix:
      - CC: ["gcc", "clang"]


meson from tarball:
  extends:
    - .fdo.distribution-image@arch
  stage: test
  script:
    - mkdir -p _tarball_build
    - tar xf libXau-*.tar.gz -C _tarball_build
    - cd _tarball_build/libXau-*
    - meson setup _builddir
    - meson configure _builddir
    - ninja -C _builddir test
  needs:
    - autotools

compare meson and autotools:
  extends:
    - .fdo.distribution-image@arch
  stage: test
  script:
    - mkdir -p $PWD/_meson_inst
    - mkdir -p $PWD/_autotools_inst
    # the prefix ends up in the pkgconfig files, so we use a symlink
    # to use the same --prefix for meson and autotools
    - ln -sf $PWD/_meson_inst $PWD/_inst
    - meson setup builddir
    - meson configure builddir --prefix=$PWD/_inst
    - ninja -C builddir install
    - ls -R _inst > _meson_inst.ls
    - rm $PWD/_inst
    - ln -sf $PWD/_autotools_inst $PWD/_inst
    - autoreconf -ivf
    - ./configure --prefix=$PWD/_inst --enable-shared --disable-static
    - make && make install
    - rm -f $PWD/_inst/lib/lib*.la
    - ls -R _inst > _autotools_inst.ls
    - diff -u $PWD/_meson_inst.ls $PWD/_autotools_inst.ls

check versions are in sync:
  extends:
    - .fdo.distribution-image@arch
  stage: test
  script:
    - autoreconf -ivf
    - ./configure --version | head -n 1 | sed -e 's/libXau configure //' > autotools.version
    - meson introspect meson.build --projectinfo | jq -r '.version' > meson.version
    - diff -u autotools.version meson.version || (echo "ERROR - autotools and meson versions not in sync" && false)
