name: Build Ubuntu RootFS

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag (e.g., 6.0.0)'
        required: true
        default: '1.glib'       

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          qemu-user-static \
          debootstrap \
          binfmt-support \
          xz-utils \
          tar

    - name: Make script executable
      run: chmod +x scripts/build-rootfs.sh

    - name: Run Ubuntu rootfs builder
      run: sudo ./scripts/build-rootfs.sh

    - name: Upload imagefs.txz as Release asset
      uses: softprops/action-gh-release@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: latest.gllib.1
        files: imagefs.txz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
